### PR TITLE
Compatibility with IJ 2024.2

### LINKED ISSUE #47: Support for 2024.2 EAP?
IDEA's early access version 2024.2 is out and it's reporting that this plugin is "marked as incompatible". I can't tell if this is a code problem or some missing metadata.

It looks like #43 was mostly metadata, hopefully support for 2024.2 will be just as easy?

### PR DESCRIPTION
**Pull request by ghik**
Fixes #47

### CODE REVIEW

**Comment by ghik** [comment]
@Krever unfortunately, some tests started failing with enigmatic exceptions and I haven't gotten yet to look into it. I'll need the new release sooner or later myself, but at this very moment - contributions welcome :)

**Comment by ghik** [comment]
I asked for help with this: https://intellij-support.jetbrains.com/hc/en-us/community/posts/19827872198674-IntelliJ-HOCON-plugin-tests-failing-after-upgrading-to-2024-2-EAP

**Comment by timaliberdov** [comment]
Hi, please try updating the [sbt-idea-plugin](https://github.com/JetBrains/sbt-idea-plugin/tags) to the latest stable `3.26.2` version. I believe this should help.

**Comment by timaliberdov** [comment]
@ghik there's also a few test failures after that, if you don't mind I can push the fix. Or can send you a patch.

**Comment by ghik** [comment]
@timaliberdov great, can you submit a PR based on this one?

**Pull request merged**
