### PR TITLE
Update IntelliJ version, initial support for 2024.1

### LINKED ISSUE #43: Support 2024.1 EAP

### PR DESCRIPTION
**Pull request by ddworak**
Closes #43 

@ghik would you like to take a look? The plugin seems to work fine on newer versions after minor changes, but I'd be very open to some pointers regarding publishing, i.e.:
1) Should we consider a separate branch for idea24?
2) What is the intended release process? I can see the pipeline, but it does not seem to have been used in the previous releases. Also, should `plugin.xml` be manually updated before release?

### CODE REVIEW

**Comment by ghik** [comment]
1. Yes, to be consistent with the convention used so far, create `idea24` branch
2. Edit `plugin.xml`, invoke `sbt packagePluginZip` and upload manually via plugin site

**Comment by ghik** [comment]
@ddworak FYI I fave no direct access to this repo anymore.

**Comment by ghik** [comment]
@ddworak that you?
image

**Comment by ddworak** [comment]
@ghik apparently so
image

**Review by ghik — APPROVED** [review]

**Comment by ghik** [comment]
@ddworak I'll do the build and update. In the meantime, I've added you as a developer to the plugin.

**Pull request merged**
